//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bcv.Client.BcvServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BcvServices.IBcvService")]
    public interface IBcvService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcvService/GetProducts", ReplyAction="http://tempuri.org/IBcvService/GetProductsResponse")]
        System.Collections.ObjectModel.ObservableCollection<Bcv.Entities.Product> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcvService/GetProducts", ReplyAction="http://tempuri.org/IBcvService/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Bcv.Entities.Product>> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcvService/GetCustomers", ReplyAction="http://tempuri.org/IBcvService/GetCustomersResponse")]
        System.Collections.ObjectModel.ObservableCollection<Bcv.Entities.Customer> GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcvService/GetCustomers", ReplyAction="http://tempuri.org/IBcvService/GetCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Bcv.Entities.Customer>> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcvService/SubmitOrder", ReplyAction="http://tempuri.org/IBcvService/SubmitOrderResponse")]
        void SubmitOrder(Bcv.Entities.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcvService/SubmitOrder", ReplyAction="http://tempuri.org/IBcvService/SubmitOrderResponse")]
        System.Threading.Tasks.Task SubmitOrderAsync(Bcv.Entities.Order order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBcvServiceChannel : Bcv.Client.BcvServices.IBcvService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BcvServiceClient : System.ServiceModel.ClientBase<Bcv.Client.BcvServices.IBcvService>, Bcv.Client.BcvServices.IBcvService {
        
        public BcvServiceClient() {
        }
        
        public BcvServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BcvServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BcvServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BcvServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Bcv.Entities.Product> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Bcv.Entities.Product>> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Bcv.Entities.Customer> GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Bcv.Entities.Customer>> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public void SubmitOrder(Bcv.Entities.Order order) {
            base.Channel.SubmitOrder(order);
        }
        
        public System.Threading.Tasks.Task SubmitOrderAsync(Bcv.Entities.Order order) {
            return base.Channel.SubmitOrderAsync(order);
        }
    }
}
